# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56de4b20a295f3eb3e6e2dbd2e82d7b4265987920233336488cc1400aafb65e82d675274054e7d4f9d72347f68b5f1f2eb4ddc9e3332868a3378b5f33d95c562

test:
  secret_key_base: 5fbe408ccc55e50b0e9483022d0e666f959d0562be68560af1cc6b4afa86401cf9d2a729320c492b2d1bd9b9a29707f0ca94e42caf3e47b49ff11c37e92bec29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
